### ISSUE TITLE
Repainting Problem on Scaled-Normalized-Vector-Strategy-(v4-1)

### ISSUE THREAD

**Issue by NeziheSozen** [capissimo/Pinescript-Laboratory#1]
Hello,

I have tried this strategy and I worked to avoid repaint problem. How can I handle repainting problem with this code?
scripts/040-Scaled-Normalized-Vector-Strategy-(v4-1).pine

Thank you in advance!
Best regards

**Comment by capissimo** [comment]
Hi,

This strat is inherently repainting. No way to avoid it. Generally speaking, strats that use any sort of indirection are the most promising.

B.R.,
Andrey

**Comment by NeziheSozen** [comment]
Hi Andrey,

Thank you for your quick reply and all your code sharing. All are instructive.

Best regards and have a nice day!
Nezihe
